version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    networks:
      - app_network  
    environment:
      PORT: 9000
      MONGO_URI: 'mongodb+srv://syedaslam1841:GRBVYk9IadDc6uVA@cluster0.n7tc4.mongodb.net/?retryWrites=true&w=majority&appName=cluster0'
      BASE_URL: http://localhost:9000
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:7
    networks:
      - app_network
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
